# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-node-app-chart.fullname" . }}
spec:
  selector:
    app: {{ include "my-node-app-chart.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
