# values.yaml
replicaCount: 1
image:
  repository: gcr.io/project-4-workndemos/my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  PORT: 3000
