# values.yaml
replicaCount: 1
image:
  repository: ghcr.io/shailenevonence/sy-helm-test/my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  PORT: 3000
