name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: project-4-workndemos
  REGION: us-central1
  ZONE: us-central1-a
  GKE_CLUSTER: sy-test
  DEPLOYMENT_NAME: randocats

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.POOL_URL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          # project_id: ${{ env.GCP_PROJECT_ID }}
          # location: ${{ env.REGION }}

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     token_format: 'access_token'
      #     workload_identity_provider: ${{ secrets.POOL_URL }}
      #     service_account: ${{ secrets.SERVICE_ACCOUNT }}
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     location: ${{ env.REGION }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
          echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-sdk
          gcloud components install kubectl  
          gcloud components install beta
          gcloud --quiet auth configure-docker

      # # Get the GKE credentials so we can deploy to the cluster
      # - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      #   with:
      #     cluster_name: ${{ env.GKE_CLUSTER }}
      #     project_id: ${{ env.GCP_PROJECT_ID }}
      #     location: ${{ env.REGION }}


      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/shailenevonence/nginx-hello-world:latest ./nginx
          docker push ghcr.io/shailenevonence/nginx-hello-world:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          gcloud container clusters get-credentials sy-test --location us-central1 --project project-4-workndemos
          helm upgrade_arg: 
            --set image.repository=ghcr.io/shailenevonence/nginx-hello-world \
            --set image.tag=latest \
            --wait
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
