name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: project-4-workndemos
  REGION: us-central1
  ZONE: us-central1-a
  GKE_CLUSTER: sy-test
  DEPLOYMENT_NAME: randocats

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup gcloud CLI
      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.POOL_URL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud auth list'

      - name: Install gcloud CLI components
        run: |
          gcloud components install kubectl
          gcloud components install beta

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/shailenevonence/sy-helm-test/nginx-hello-world:latest ./nginx
          docker push ghcr.io/shailenevonence/sy-helm-test/nginx-hello-world:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --region $REGION --project $GCP_PROJECT_ID
          helm upgrade $DEPLOYMENT_NAME ${GKE_PROJECT}-cluster \
            --set image.repository=ghcr.io/shailenevonence/sy-helm-test/nginx-hello-world \
            --set image.tag=latest \
            --wait
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
