name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO
  GCP_PROJECT_ID: $GCP_PROJECT_ID
  REGION: $REGION
  ZONE: $ZONE
  GKE_CLUSTER: sy-test
  DEPLOYMENT_NAME: randocats

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.POOL_URL }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          project_id: ${{ env.GCP_PROJECT_ID }}
          gcp_region: ${{ env.REGION }}

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/shailenevonence/nginx-hello-world:latest ./nginx
          echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $ --password-stdin
          docker push ghcr.io/shailenevonence/nginx-hello-world:latest

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy with Helm
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER \
            --location $REGION && \
          helm upgrade --install nginx-hello-world ./nginx-hello-world \
            --set image.repository=ghcr.io/sy-helm-test/nginx-hello-world \
            --set image.tag=${{ github.sha }} \
            --wait && \
          kubectl rollout status deployment/$DEPLOYMENT_NAME && \
          kubectl get services -o wide
